/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fant_util_CompanyExtracter */

#ifndef _Included_com_fant_util_CompanyExtracter
#define _Included_com_fant_util_CompanyExtracter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fant_util_CompanyExtracter
 * Method:    search
 * Signature: (Ljava/lang/String;Z)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_fant_util_CompanyExtracter_search
(JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_fant_util_CompanyExtracter
 * Method:    init
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_fant_util_CompanyExtracter_init
(JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_fant_util_CompanyExtracter
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fant_util_CompanyExtracter_destroy
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
